services:

  php:
    build:
      context: ./docker/php
      args:
        FROM_IMAGE: php:8.1-fpm
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test